/* 
 * Project       : Bachelor Thesis - Sudoku game implementation as portlet
 * Document      : GameType.java
 * Author        : Ondřej Fibich <xfibic01@stud.fit.vutbr.cz>
 * Organization: : FIT VUT <http://www.fit.vutbr.cz>
 */

package org.gatein.portal.examples.games.sudoku.entity.datatype;

/**
 * Game Type Class
 * Specifies types of a game
 *
 * @author Ondřej Fibich
 */
public enum GameType
{
    /**
     * A game was generated by the GameGenerator class
     */
    GENERATED,
    
    /**
     * A game was gained from a remote service
     */
    SERVICE;
}
